flask-message-board/messageboard/messageboard/models.py
# coding=utf-8
from . import db
from . import login_manager
from datetime import datetime
from flask_login import UserMixin


# 用户类
class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(32))
    salt = db.Column(db.String(32))

    # 用户和留言类连接
    message = db.relationship('Message', backref='user', lazy='dynamic')

    __table_args__ = {
        'mysql_charset': 'utf8'
    }

    def __init__(self, username, password, salt=''):
        self.username = username
        self.password = password
        self.salt = salt

    def __repr__(self):
        return '<User %d %s>' % (self.id, self.username)


# 留言类
class Message(db.Model):
    __tablename__ = 'message'
    id = db.Column(db.Integer, primary_key=True)
    # 外键
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    msg = db.Column(db.String(1024))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = {
        'mysql_charset': 'utf-8'
    }

    def __init__(self, author_id, msg, timestamp):
        self.author_id = author_id
        self.msg = msg
        self.timestamp = timestamp

    def __repr__(self):
        return '<Message %d %s>' % (self.id, self.msg)


# login_manager 返回用户对象，回调，无效返回None
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

flask-message-board/messageboard/messageboard/__init__.py
# -*- encoding=UTF-8 -*-
import sys

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
import pymysql

pymysql.install_as_MySQLdb()

app = None
# db实例化
db = SQLAlchemy(use_native_unicode='utf-8')
bootstrap = Bootstrap()
# login-manager处理登入，会话管理，管理长时间记住用户的会话
login_manager = LoginManager()
login_manager.session_protection = 'strong'
# login_view设置登陆页面的端点
login_manager.login_view = 'reglogin.login'

# 导入import模块
import importlib

importlib.reload(sys)


def create_app():
    global app
    # app配置数据库
    app = Flask(__name__, template_folder='templates')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:root@localhost:3306/testdb'  # 配置数据库,自己填上
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    # secret_key
    app.config['SECRET_KEY'] = 'MONKEY'

    # db初始化
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)

    # 引入视图和model
    from .reglogin import reglogin_view as login_blueprint
    from .bbs import bbs_view as bbs_blueprint

    # app加载登录注册蓝图
    app.register_blueprint(login_blueprint)
    # app加载留言板蓝图
    app.register_blueprint(bbs_blueprint)

    return app

flask-message-board/messageboard/messageboard/bbs/__init__.py
# coding=utf-8
from flask import Blueprint
bbs_view = Blueprint('bbs_view', __name__)

from messageboard.bbs import views

flask-message-board/messageboard/messageboard/bbs/views.py
# coding=utf-8
from . import bbs_view
from flask import render_template, redirect, flash, url_for, request
from .form import MessageForm
from flask_login import current_user
from messageboard.models import Message, db
import datetime
from flask_paginate import Pagination,get_page_parameter


# 主页
@bbs_view.route('/', methods={'get', 'post'},endpoint='index')
def index():
    form = MessageForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            nowTime = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            message = Message(current_user.id, form.msg.data, nowTime)
            db.session.add(message)
            db.session.commit()
            flash('留言成功')
            redirect('/')
        else:
            flash('留言失败，请登录账号后进行留言')
            redirect('/')
    page = int(request.args.get('page', 1))  # 当前页数
    per_page = int(request.args.get('per_page', 5))  # 设置每页数量
    paginate = Message.query.order_by(Message.timestamp.desc()).paginate(page, per_page, error_out=False)
    return render_template('index.html', form=form, paginate=paginate)


flask-message-board/messageboard/messageboard/reglogin/__init__.py
# coding=utf-8
from flask import Blueprint

reglogin_view = Blueprint('reglogin_view', __name__)
from messageboard.reglogin import views

flask-message-board/messageboard/messageboard/reglogin/views.py
# coding=utf-8
from . import reglogin_view
from ..models import User, db
import hashlib
import random
from flask import render_template, redirect, request, flash, url_for
from flask_login import login_user, logout_user, login_required
from .form import LoginForm, RegisterForm, SearchForm, UpdateForm
from messageboard.models import Message, db
from flask_login import current_user
import datetime


# 登录页
@reglogin_view.route('/login/', methods={'get', 'post'})
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None:
            # 密码正确验证
            m = hashlib.md5()
            m.update((form.password.data + user.salt).encode("utf-8"))
            print
            if m.hexdigest() != user.password:
                flash('密码输入错误')
                return redirect('/login')
            login_user(user)
            flash('登录成功')
            return redirect('/')
        else:
            flash('用户或密码错误')
    return render_template('login.html', form=form)


# 注册页
@reglogin_view.route('/register/', methods={'get', 'post'})
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            # 查看用户是否存在数据库中
            user = User.query.filter_by(username=form.username.data).first()
            if user is not None:
                flash('用户名已经存在')
                return redirect('/register')
            # 用户名不存在注册
            # 密码加md5+盐
            salt = ''.join(random.sample('0123456789abcdefghigklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', 10))
            m = hashlib.md5()
            m.update((form.password.data + salt).encode("utf-8"))
            password = m.hexdigest()
            # 新用户提交入库
            user = User(form.username.data, password, salt)
            try:
                # 数据库提交
                db.session.add(user)
                db.session.commit()
            except Exception as e:
                print(e)
                flash('注册成功')
                db.session.rollback()
            return redirect(url_for('reglogin_view.login'))

    return render_template('register.html', form=form)


# 登出页
@reglogin_view.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('你已退出登录')
    return redirect(url_for('reglogin_view.login'))


# 查询页
@reglogin_view.route('/search/', methods={'get', 'post'})
def search():
    form = SearchForm(request.form)
    if form.validate_on_submit():
        messages = Message.query.filter(
            Message.msg.like("%" + form.username.data + "%") if form.username.data is not None else "").all()
        return render_template('search.html', form=form, messages=messages)
    else:
        messages = Message.query.order_by(Message.timestamp.desc()).all()
        return render_template('search.html', form=form, messages=messages)


# 个人页
@reglogin_view.route('/person/', methods={'get', 'post'})
def person():
    page = int(request.args.get('page', 1))  # 当前页数
    per_page = int(request.args.get('per_page', 5))  # 设置每页数量
    paginate = Message.query.filter_by(author_id=current_user.id).paginate(page, per_page, error_out=False)
    return render_template('person.html', paginate=paginate)


# 删除页
@reglogin_view.route('/delete/<message_id>', methods={'get', 'post'})
def delete(message_id):
    message = Message.query.get(message_id)
    try:
        db.session.delete(message)
        db.session.commit()
    except Exception as e:
        print(e)
        flash("删除成功")
        db.session.rollback()
    return redirect('/person')


# 修改页
@reglogin_view.route('/update/<message_id>', methods={'get', 'post'})
def update(message_id):
    form = UpdateForm()
    if form.validate_on_submit():
        nowTime = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        try:
            db.session.execute("update Message set msg = '"+form.username.data+"'where id ='"+message_id+"'")
            db.session.execute("update Message set timestamp = '" + nowTime + "'where id ='" + message_id + "'")
            db.session.commit()
        except Exception as e:
            print(e)
            flash('修改成功')
            db.session.rollback()
        return redirect('/person')
    else:
        return render_template('update.html', form=form)

flask-message-board/messageboard/messageboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% extends "bootstrap/base.html" %}
<html>
<head>
    <title>{% block title %}留言板{% endblock %}</title>
    <meta charset="UTF-8">
</head>
<body>
    {% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">留言板</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">主页</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('reglogin_view.search') }}">查询</a></li>
                    {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('reglogin_view.person') }}">个人中心</a></li>
                    <li><a href="{{ url_for('reglogin_view.logout') }}">注销</a></li>
                    {% else %}
                    <li><a href="{{ url_for('reglogin_view.login') }}">登录</a></li>
                    <li><a href="{{ url_for('reglogin_view.register') }}">注册</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

flask-message-board/messageboard/messageboard/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
<html>
<head>
    <title>{% block title %}首页{% endblock %}</title>
    <meta charset="UTF-8">
</head>
<body>
    {% block content %}
        <div class="page-header">
            <div class="container">
                <h1>
                    欢迎进入留言板,
                    {% if current_user.is_authenticated %}
                    {{current_user.username}}
                    {% else %}
                    请登录
                    {% endif %}
                </h1>
            </div>
            <div class="container">
                <h3>
                    {% for message in get_flashed_messages() %}
                    {{ message }}
                    {% endfor %}
                </h3>
            </div>
        </div>

        <div class="container">
            <form method="post" id="bbsform" accept-charset="utf-8" onsubmit="document.charset='utf-8'">
                {{ wtf.quick_form(form) }}
            </form>
        </div>

        <div class="container">
            <ul class="Message">
                <h4>
                    {% for message in paginate.items%}
                        <li>
                            <div>
                                {{message.user.username}}
                                <div style="text-align: right;">{{message.timestamp}}</div>
                            </div>
                            <div>
                                {{message.msg}}
                            </div>
                            <br>
                        </li>
                    {% endfor %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination">

                            总页数：{{ paginate.pages }}
                            数据总条数:{{ paginate.total }}
                            当前页数:{{ paginate.page }}
                            <a href="/?page=1">首页</a>
                            {% if paginate.has_prev %}
                                <a href="/?page={{ paginate.prev_num }}">上一页</a>
                            {% endif %}
                            {% if paginate.has_next %}
                                <a href="/?page={{ paginate.next_num }}">下一页</a>
                            {% endif %}
                            <a href="/?page={{paginate.pages}}">尾页</a>
                            页码:
                            {% for i in paginate.iter_pages() %}
                                <a href="/?page={{ i }}">{{ i }}</a>
                            {% endfor %}
                        </ul>
                    </nav>
                </h4>
            </ul>
            </div>
    {% endblock %}
</body>
</html>




flask-message-board/messageboard/messageboard/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}登录{% endblock %}

<meta charset="UTF-8">
{% block content %}
    <div class="page-header">
        <div class="container">
            <h1>登录</h1>
        </div>
        <div class="container">
            <h3>
                {% for message in get_flashed_messages() %}
                {{ message }}
                {% endfor %}
            </h3>
        </div>
    </div>
    <div class="container">
        <form method="post" id="loginform">
            {{ wtf.quick_form(form) }}
        </form>
    </div>
{% endblock %}

flask-message-board/messageboard/messageboard/templates/person.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}个人中心{% endblock %}
<meta charset="UTF-8">
{% block content %}
    <div class="page-header">
        <div class="container">
            <h1>个人中心</h1>
        </div>
    </div>
    <div>
        <ul class="Message">
            <h4>
                {% for message in paginate.items%}
                    <li>
                        <div>
                            {{message.user.username}}
                            <div style="text-align: right;">
                                {{message.timestamp}}
                                <a href="{{url_for('reglogin_view.delete',message_id=message.id)}}">删除</a>
                                <a href="{{url_for('reglogin_view.update',message_id=message.id)}}">修改</a>
                            </div>
                        </div>
                        <div>
                            {{message.msg}}
                        </div>
                        <br>
                    </li>
                {% endfor %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        总页数：{{ paginate.pages }}
                        数据总条数:{{ paginate.total }}
                        当前页数:{{ paginate.page }}
                        <a href="/person/?page=1">首页</a>
                        {% if paginate.has_prev %}
                            <a href="/person/?page={{ paginate.prev_num }}">上一页</a>
                        {% endif %}
                        {% if paginate.has_next %}
                            <a href="/person/?page={{ paginate.next_num }}">下一页</a>
                        {% endif %}
                            <a href="/person/?page={{paginate.pages}}">尾页</a>
                        页码:
                        {% for i in paginate.iter_pages() %}
                            <a href="/person/?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                    </ul>
                </nav>
            </h4>
        </ul>
    </div>
{% endblock %}

flask-message-board/messageboard/messageboard/templates/register.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}注册{% endblock %}
<meta charset="UTF-8">
{% block content %}
    <div class="page-header">
        <div class="container">
            <h1>注册</h1>
        </div>
        <div class="container">
            <h3>
                {% for message in get_flashed_messages() %}
                {{ message }}
                {% endfor %}
            </h3>
        </div>
    </div>
    <div class="container">
        <form method="post">
            {{ wtf.quick_form(form) }}
        </form>
    </div>
{% endblock %}

flask-message-board/messageboard/messageboard/templates/search.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}查询{% endblock %}

<meta charset="UTF-8">
{% block content %}
    <div class="page-header">
        <div class="container">
            <h1>查询</h1>
        </div>

    </div>
    <div class="container">
        <form method="post" id="loginform">
            {{ wtf.quick_form(form) }}
        </form>
    </div>
    <div>
        <ul class="Message">
            <h4>{% for message in messages%}
                <li>
                    <div>
                        {{message.user.username}}
                        <div style="text-align: right;">{{message.timestamp}}</div>
                    </div>
                    <div>
                        {{message.msg}}
                    </div>
                    <br>
                </li>
                {% endfor %}
            </h4>
        </ul>
    </div>
{% endblock %}


flask-message-board/messageboard/messageboard/templates/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %}修改{% endblock %}

<meta charset="UTF-8">
{% block content %}
    <div class="page-header">
        <div class="container">
            <h1>修改</h1>
        </div>

    </div>
    <div class="container">
        <form method="post" id="loginform">
            {{ wtf.quick_form(form) }}
        </form>
    </div>
{% endblock %}